### PR TITLE
handle case when schema info is present but value is null

### PR DESCRIPTION
**Pull request by twiechert**

### CODE REVIEW

**Comment by twiechert** [comment]
Actually I'm unsure if that is the best solution.

In case of a tombstone it might be actually better to forward the record without any changes.

**Comment by cricket007** [comment]
Hey @twiechert , thanks for the contribution! 

> might be actually better to forward the record without any changes

Agreed. Could you give an example of when the schema is non-null but the value is null?

Also, do you think the message key logic should also allow for null values to be passed though in a similar fashion, rather than having the skip configuration?

**Comment by twiechert** [comment]
hi @cricket007 ,

consider for example the comcast mirrortool:

```
records.add(new SourceRecord(sourcePartition, sourceOffset, destinationTopic, null, Schema.OPTIONAL_BYTES_SCHEMA, krecord.key(), Schema.OPTIONAL_BYTES_SCHEMA, krecord.value(), krecord.timestamp(), destinationHeaders));
```

replicating a tombstone, thus value null but setting the schema member to  `Schema.OPTIONAL_BYTES_SCHEMA`

> Also, do you think the message key logic should also allow for null values to be passed though in a similar fashion, rather than having the skip configuration?

I think a null-key record is rarely useful but I also think the schema registry smt should not exclude such records by default (option would be fine).

**Comment by cricket007** [comment]
> should not exclude such records by default

Right, thus why the config option is currently true, however I am throwing an exception when the keys are included and null, so I would accept if this PR adjusted that logic as well for setting the `updatedKey` to be null for when `includeKeys == true && key == null`

```java
        if (includeKeys) { // default = true
            if (key == null) {
                throw new ConnectException("Unable to copy record key schemas for null keys. Set '" + ConfigName.INCLUDE_KEYS + "=false'.");
}

```

**Comment by cricket007** [comment]
Or maybe having to manually set `include.message.key = false` is good enough and having the logic for `includeKeys ? updatedKey : r.key()` is adequate. Personally, I can't really decide what is most user-friendly.

**Comment by twiechert** [comment]
Well, I think the name `include.message.key` is a bit misleading, since it it always included. Question is if it is transformed or not.

I would personally say to never skip a record. While it might not be best practice to mix records with and without schema inside one topic, I don't think the smt should (by default) simply skip the records without schema in such case.

One could think of including options like skipNullKey/skipNullValue which would explicitly allow for that.

**Comment by cricket007** [comment]
Incorporated parts of this change in #8

**Pull request closed without merging**
